// <auto-generated />
using System;
using LogisticControl.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("api")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticControl.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("Complement")
                        .HasColumnType("text")
                        .HasColumnName("complement");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("p_k_addresses");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("i_x_addresses_company_id");

                    b.ToTable("addresses", "api");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Pedro Leopoldo",
                            CompanyId = 1,
                            Neighborhood = "Manoel Carlos",
                            Number = 560,
                            State = "MG",
                            Street = "Av. Lincoln Diogo Viana"
                        },
                        new
                        {
                            Id = 2,
                            City = "Belo Horizonte",
                            CompanyId = 2,
                            Neighborhood = "Olhos D'Água",
                            Number = 255,
                            State = "MG",
                            Street = "R. São Vicente"
                        },
                        new
                        {
                            Id = 3,
                            City = "Lagoa Santa",
                            CompanyId = 2,
                            Neighborhood = "Vila Asas",
                            Number = 333,
                            State = "MG",
                            Street = "R. das Goiabeiras"
                        });
                });

            modelBuilder.Entity("LogisticControl.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PartnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partnership_type");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("p_k_companies");

                    b.ToTable("companies", "api");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mecbrun Industrial",
                            PartnershipType = "Cliente",
                            Phone = "(31) 96523-4789"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Geosol Geologia e Sondagens",
                            PartnershipType = "Cliente",
                            Phone = "(31) 99874-3642"
                        });
                });

            modelBuilder.Entity("LogisticControl.Domain.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("p_k_drivers");

                    b.ToTable("drivers", "api");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amaro",
                            Phone = "(31) 95648-7854"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Higor",
                            Phone = "(31) 94756-5467"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samuel",
                            Phone = "(31) 98965-4756"
                        });
                });

            modelBuilder.Entity("LogisticControl.Domain.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("Finalization")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finalization");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<DateTime>("Opening")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("opening");

                    b.Property<DateTime?>("Realization")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("realization");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_routes");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("i_x_routes_driver_id");

                    b.ToTable("routes", "api");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            Finalization = new DateTime(2024, 11, 13, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Opening = new DateTime(2024, 11, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Realization = new DateTime(2024, 11, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Finalizada"
                        },
                        new
                        {
                            Id = 2,
                            Opening = new DateTime(2024, 11, 14, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pendente"
                        });
                });

            modelBuilder.Entity("LogisticControl.Domain.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("adress_id");

                    b.Property<string>("DriverObservation")
                        .HasColumnType("text")
                        .HasColumnName("driver_observation");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("Responsible")
                        .HasColumnType("text")
                        .HasColumnName("responsible");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusItem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_item");

                    b.Property<string>("Tracking")
                        .HasColumnType("text")
                        .HasColumnName("tracking");

                    b.Property<string>("TrackingType")
                        .HasColumnType("text")
                        .HasColumnName("tracking_type");

                    b.HasKey("Id")
                        .HasName("p_k_services");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("i_x_services_adress_id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_services_route_id");

                    b.ToTable("services", "api");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Priority = "Alta",
                            RouteId = 1,
                            ServiceType = "Entrega",
                            Status = "Realizado",
                            StatusItem = "Liberado",
                            Tracking = "2024/586",
                            TrackingType = "NF"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Observation = "Material pesado",
                            Priority = "Media",
                            Responsible = "Carlos",
                            RouteId = 1,
                            ServiceType = "Coleta",
                            Status = "NaoRealizado",
                            StatusItem = "Liberado",
                            Tracking = "547",
                            TrackingType = "OS"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            Priority = "Alta",
                            RouteId = 2,
                            ServiceType = "Entrega",
                            Status = "EmAndamento",
                            StatusItem = "Liberado",
                            Tracking = "2024/587",
                            TrackingType = "NF"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 3,
                            Priority = "Baixa",
                            ServiceType = "Coleta",
                            Status = "Pendente",
                            StatusItem = "NaoLiberado",
                            Tracking = "548",
                            TrackingType = "OS"
                        });
                });

            modelBuilder.Entity("LogisticControl.Domain.Address", b =>
                {
                    b.HasOne("LogisticControl.Domain.Company", "Company")
                        .WithMany("Addresses")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("f_k_addresses__companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LogisticControl.Domain.Route", b =>
                {
                    b.HasOne("LogisticControl.Domain.Driver", "Driver")
                        .WithMany("Routes")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("f_k_routes_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("LogisticControl.Domain.Service", b =>
                {
                    b.HasOne("LogisticControl.Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .HasConstraintName("f_k_services_addresses_adress_id");

                    b.HasOne("LogisticControl.Domain.Route", "Route")
                        .WithMany("Services")
                        .HasForeignKey("RouteId")
                        .HasConstraintName("f_k_services_routes_route_id");

                    b.Navigation("Address");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("LogisticControl.Domain.Company", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("LogisticControl.Domain.Driver", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("LogisticControl.Domain.Route", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
