// <auto-generated />
using System;
using LogisticControl.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticControl.Domain.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<int>("Company_Id")
                        .HasColumnType("integer")
                        .HasColumnName("company__id");

                    b.Property<string>("Complement")
                        .HasColumnType("text")
                        .HasColumnName("complement");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("p_k_adresses");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("i_x_adresses_company_id");

                    b.HasIndex("Company_Id")
                        .HasDatabaseName("i_x_adresses_company__id");

                    b.ToTable("adresses");
                });

            modelBuilder.Entity("LogisticControl.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PartnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partnership_type");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("p_k_companies");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("LogisticControl.Domain.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("p_k_drivers");

                    b.ToTable("drivers");
                });

            modelBuilder.Entity("LogisticControl.Domain.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int?>("Driver_Id")
                        .HasColumnType("integer")
                        .HasColumnName("driver__id");

                    b.Property<DateTime?>("Finalization")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalization");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<DateTime>("Opening")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opening");

                    b.Property<DateTime?>("Realization")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realization");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_routes");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("i_x_routes_driver_id");

                    b.HasIndex("Driver_Id")
                        .HasDatabaseName("i_x_routes_driver__id");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("LogisticControl.Domain.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Adress_Id")
                        .HasColumnType("integer")
                        .HasColumnName("adress__id");

                    b.Property<string>("DriverObservation")
                        .HasColumnType("text")
                        .HasColumnName("driver_observation");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("Responsible")
                        .HasColumnType("text")
                        .HasColumnName("responsible");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<int?>("Route_Id")
                        .HasColumnType("integer")
                        .HasColumnName("route__id");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusItem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_item");

                    b.Property<string>("Tracking")
                        .HasColumnType("text")
                        .HasColumnName("tracking");

                    b.Property<string>("TrackingType")
                        .HasColumnType("text")
                        .HasColumnName("tracking_type");

                    b.HasKey("Id")
                        .HasName("p_k_services");

                    b.HasIndex("Adress_Id")
                        .HasDatabaseName("i_x_services_adress__id");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_services_route_id");

                    b.HasIndex("Route_Id")
                        .HasDatabaseName("i_x_services_route__id");

                    b.ToTable("services");
                });

            modelBuilder.Entity("LogisticControl.Domain.Adress", b =>
                {
                    b.HasOne("LogisticControl.Domain.Company", null)
                        .WithMany("Adresses")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("f_k_adresses__companies_company_id");

                    b.HasOne("LogisticControl.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_Id")
                        .IsRequired()
                        .HasConstraintName("f_k_adresses__companies_company__id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LogisticControl.Domain.Route", b =>
                {
                    b.HasOne("LogisticControl.Domain.Driver", null)
                        .WithMany("Routes")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("f_k_routes_drivers_driver_id");

                    b.HasOne("LogisticControl.Domain.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("Driver_Id")
                        .HasConstraintName("f_k_routes_drivers_driver__id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("LogisticControl.Domain.Service", b =>
                {
                    b.HasOne("LogisticControl.Domain.Adress", "Adress")
                        .WithMany()
                        .HasForeignKey("Adress_Id")
                        .HasConstraintName("f_k_services_adresses_adress__id");

                    b.HasOne("LogisticControl.Domain.Route", null)
                        .WithMany("Services")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("f_k_services_routes_route_id");

                    b.HasOne("LogisticControl.Domain.Route", "Route")
                        .WithMany()
                        .HasForeignKey("Route_Id")
                        .HasConstraintName("f_k_services_routes_route__id");

                    b.Navigation("Adress");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("LogisticControl.Domain.Company", b =>
                {
                    b.Navigation("Adresses");
                });

            modelBuilder.Entity("LogisticControl.Domain.Driver", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("LogisticControl.Domain.Route", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
