<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogisticControl.Repository\LogisticControl.Repository.csproj" />
  </ItemGroup>

</Project>
